name: moh_phi_project
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  jwt_decoder: ^2.0.1


  
  cupertino_icons: ^1.0.6
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.1.0
  charts_flutter: ^0.12.0 
  fl_chart: ^0.45.1

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

 
  assets:
    - lib/assets/images/login.jpg
    - lib/assets/images/log.png
    - lib/assets/images/user.png
    - lib/assets/images/add.png
    - lib/assets/images/chart.png
    - lib/assets/images/patient.png
    - lib/assets/images/phi.png
    - lib/assets/images/settings.png
    - lib/assets/images/about.png
    - lib/assets/images/patientrecords.png
    - lib/assets/images/philist.png
    - lib/assets/images/aboutpage.jpg
    


  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/fonts/Pacifico-Regular.ttf

    - family: Source Sans Regular
      fonts:
        - asset: lib/fonts/SourceSans3-Regular.ttf
